name: component
description: A new Flutter package project.
version: 0.0.2
homepage: "https://kodingworks.io/"

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  preferences:
    path: ../preferences
  l10n:
    path: ../l10n
  dependencies:
    path: ../dependencies
  core:
    path: ../../core
  settings:
    path: ../../features/settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
