name: trackingworks
description: A new Flutter project.

# Build android app need add --no-shrink to fix image_picker in release mode 

publish_to: "none"
version: 1.0.16+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ---------------------- MODULE -------------------
  component:
    path: shared/component
  core:
    path: core
  dependencies:
    path: shared/dependencies
  l10n:
    path: shared/l10n
  preferences:
    path: shared/preferences

  # ------------- Feature Module
 
  attendance:
    path: features/employee/attendance
  auth:
    path: features/auth
  leave:
    path: features/employee/leave
  notice:
    path: features/employee/notice
  payroll:
    path: features/employee/payroll
  profile:
    path: features/employee/profile
  resign:
    path: features/employee/resign
  settings:
    path: features/settings
  files:
    path: features/files
  main:
    path: features/main
  

  # -------------------- END MODULE -----------------
dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/images/
    - assets/images/marker/
    - assets/images/flags/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Icons_new
      fonts:
        - asset: assets/fonts/Icons_new.ttf
    - family: TicketingIcons
      fonts:
        - asset: assets/fonts/TicketingIcons.ttf
    - family: AppIcon2
      fonts:
        - asset: assets/fonts/AppIcons2.ttf
