name: build_pr

on:
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    - name: Build debug akp
      run: |
        cd example
        flutter build apk --debug
    - name: Build debug ios app
      run: |
        cd example
        flutter build ios --debug --no-codesign
