name: core
description: A new Flutter package.
version: 0.0.1
homepage: "https://kodingworks.io/"

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../shared/dependencies
  l10n:
    path: ../shared/l10n

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
