name: settings
description: A new Flutter package project.
version: 0.0.2
homepage: "https://kodingworks.io"

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  dependencies:
    path: ../../shared/dependencies
  preferences:
    path: ../../shared/preferences
  l10n:
    path: ../../shared/l10n
  component:
    path: ../../shared/component

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: 