name: flutter_device_id
description: A new flutter plugin project.
version: 0.0.1
homepage: "https://wisnuwiry.space"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: space.wisnuwiry.flutter_device_id
        pluginClass: FlutterDeviceIdPlugin
      ios:
        pluginClass: FlutterDeviceIdPlugin
