// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const _kFontPkg = null;

  static const IconData walletLine =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData employeeLine =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeHideLine =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeLine =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderOpenLine =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData houseLine =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData houseSolid =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imageSolid =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infoCircleLine =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationLine =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userLine =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filterSolid =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lockLine =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loginLine =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencilSolid =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timesCircleLine =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlockSolid =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usersLine =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playSolid =
      IconData(0xe9bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasksLine =
      IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasksSolid =
      IconData(0xe9eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emailLine =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layersLine =
      IconData(0xeae1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layersSolid =
      IconData(0xeae2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobileSolid =
      IconData(0xeaf9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phoneHandsetLine =
      IconData(0xeb11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData languageLine =
      IconData(0xeb8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lockReset =
      IconData(0xebc6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minutemailer =
      IconData(0xebc7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messageSquareOutline =
      IconData(0xebc8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationSolid =
      IconData(0xebc9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userSolid =
      IconData(0xebca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapMarkerLine =
      IconData(0xebcb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockLine =
      IconData(0xebcd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sadFaceLine =
      IconData(0xebce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filesGroupLine =
      IconData(0xebcf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xebd0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarLine =
      IconData(0xebd1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tagLine =
      IconData(0xebd3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsisVertical =
      IconData(0xebd4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapMarkerSolid =
      IconData(0xebd5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleteLine =
      IconData(0xebd6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viewLine =
      IconData(0xebd7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp =
      IconData(0xebd8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
