name: home_employee
description: A new Flutter package.
version: 0.0.2
homepage: "https://kodingworks.io/"

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  core:
    path: ../../../core
  component:
    path: ../../../shared/component
  dependencies:
    path: ../../../shared/dependencies
  l10n:
    path: ../../../shared/l10n
  preferences:
    path: ../../../shared/preferences
  profile:
    path: ../profile
  notice:
    path: ../notice
  auth:
    path: ../../auth
  attendance:
    path: ../attendance

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
